### ISSUE TITLE
too demo

### ISSUE THREAD

**Issue by ms0ur** [Jeno7u/demo-rep#2]
make it not too demo. make it useful

- [ ] write a AAA game in c++ by yourself
- [ ] create a c++ high-efficiency application for a NASA for calculating the universe size
- [ ]  recreate an assembler

**Comment by Jeno7u** [comment]
Later.

**Comment by ms0ur** [comment]
Now.

**Comment by ms0ur** [comment]
![image](https://github.com/user-attachments/assets/39b04d51-4188-4258-b177-fa05f5a8acf3)
